sudo: required

services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t testbox .

script:
    - docker run -e CI=true testbox npm run test

deploy: 
    provider: elasticbeanstalk
    region: "eu-west-3"
    app: "dockertest2"
    env: "Dockertest2-env"
    bucket_name: "elasticbeanstalk-eu-west-3-596643046063"
    bucket_path: "dockertest2"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY